ECHO OFF

ECHO ACQUIRING JAVA JDK 11...
ECHO Downloading...
..\tools\curl\bin\curl.exe "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip" --output ..\tools\java\jdk11.zip
ECHO Unzipping...
powershell Expand-Archive ..\tools\java\jdk11.zip -DestinationPath ..\tools\java
DEL ..\tools\java\jdk11.zip
ECHO JAVA ACQUIRED.