ECHO OFF

SET /P INSTALLJAVA=Would you like to install Java 8 (Y/[N])?
IF %INSTALLJAVA% == y SET JAVATRUE=1
IF %INSTALLJAVA% == Y SET JAVATRUE=1
IF DEFINED JAVATRUE (
    ECHO INSTALLING JAVA...
    ..\tools\java\jre-8u261-windows-i586-iftw.exe
    ECHO JAVA INSTALLED.
) ELSE (
    ECHO SKIPPING JAVA INSTALLATION.
)